### ISSUE TITLE
To allow 'overwrite' in writeHumanEvent_PfSI

### ISSUE THREAD

**Issue by suyunkang** [smitdave/MASH#1]
Here's the edited code, it gives the user a choice of whether to overwrite files or not: 

writeHumanEvent_PfSI <- function (directory, fileName, overWrite = FALSE)
{
  if (!dir.exists(paste0(directory, "OUTPUT"))) {
    dir.create(paste0(directory, "OUTPUT"), recursive = T)
  }
  if (!overWrite & file.exists(paste0(directory, "OUTPUT/", fileName))) {
    stop("writeHumanEvent_PfSI cannot write to a file that already exists!")
  }
  con = file(description = paste0(directory, "OUTPUT/", fileName),
             open = "wt")
  humanHistories = lapply(HUMANS, function(x) {
    list(eventT = x$Pathogens$Pf$eventT, events = x$Pathogens$Pf$events)
  })
  humanID = sapply(HUMANS, function(x) {
    x$myID
  })
  names(humanHistories) = paste0("human", humanID)
  writeLines(text = jsonlite::toJSON(x = humanHistories, pretty = TRUE),
             con = con)
  close(con)
}

**Comment by slwu89** [comment]
Thanks! I just made the changes official and updated the documentation!
